version: "3"
services:
  react-app:
    image: react-app-dev
    env_file: ./client/.env
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    env_file: ./server/.env
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
networks:
  mern-app:
    driver: bridge